# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
variables:
  JEKYLL_ENV: production
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

pages:
  image: ruby:2.3
  stage: deploy
  tags:
    - asprunner
  before_script:
    # minify js
    - curl -X POST -s --data-urlencode 'input@assets/js/visualization/visualization.js' https://javascript-minifier.com/raw > assets/js/visualization/visualization.min.js
    - curl -X POST -s --data-urlencode 'input@assets/js/visualization/compatibility.js' https://javascript-minifier.com/raw > assets/js/visualization/compatibility.min.js
    - rm assets/js/visualization/visualization.js
    - rm assets/js/visualization/compatibility.js
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
