# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Studie zur Zukunft des Karosseriebaus - Karosseriebau 4.0
author: Marcel Todtermuschke, Antje Ahrens, Patrick Alexander Schmidt
email: karobau4.0@iwu.fraunhofer.de
description: > # this means to ignore newlines until "baseurl:"
  A project site and blog.

# quote from the gitlab documentation:
# For example, for a Jekyll site, the baseurl is defined in the Jekyll configuration file, _config.yml.
# If your website URL is https://john.gitlab.io/blog/, you need to add this line to _config.yml: baseurl: "/blog"
baseurl: "/visualisierung-karobau40"

sass:
  style: compressed

highlighter: cyan
#HARA: DID NOT CHANGE SITE

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md", "karobau40", "python", "Gemfile", "Gemfile.lock", "jsdoc.json", "LICENSE"]
