# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Studie zur Zukunft des Karosseriebaus - Karosseriebau 4.0
author: Marcel Todtermuschke, Antje Ahrens, Patrick Alexander Schmidt
email: karobau4.0@iwu.fraunhofer.de
description: >
  Studie zur Zukunft des Karosseriebaus - Karosseriebau 4.0

sass:
  style: compressed

highlighter: cyan

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag

compress_html:
  blanklines: true
  comments: all

# Build settings
markdown: kramdown
exclude: [ "README.md", "karobau40", "python", "Gemfile", "Gemfile.lock", "jsdoc.json", "LICENSE", ".idea" ]
