name: CI

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    # TODO: put all of this in a npm package.json, so we only need to run npm install && npm run minify
    - run: npm install terser -g
    - run: terser assets/js/visualization/visualization.js --compress --mangle --output assets/js/visualization/visualization.min.js 
    - run: terser assets/js/visualization/compatibility.js --compress --mangle --output assets/js/visualization/compatibility.min.js 
    - run: terser assets/js/contact/contact.js --compress --mangle --output assets/js/contact/contact.min.js 
    
    # Auto commits minified files to the repository
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: 'assets/js'
        commit_message: "Github Action: Auto Minified JS files"
        branch: ${{ github.ref }}
