# This is a basic workflow to help you get started with Actions

name: OnSchedule

# Examples for different schedules (all times in UTC)
# every sunday at 20:00             '0 20 * * 0'
# every day at midnight             '0 0 * * *'
# every 2 hours during work hours   '30 5-17/2 * * 1-5'
# there may be some delays due to availability of github runners
on:
  schedule:
    - cron: '30 5-17/2 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      working-directory: ./python
      run: pip install -r requirements.txt
    - name: Fetch Limesurvey
      working-directory: ./python
      env:
        LIMESURVEY_PASSWORD: ${{ secrets.LIMESURVEY_PASSWORD }}
        LIMESURVEY_URL: ${{ secrets.LIMESURVEY_URL }}
        LIMESURVEY_USERNAME: ${{ secrets.LIMESURVEY_USERNAME }}
      run: |
        python get_limesurvey_results.py
        mv limesurvey_data.js ../assets/js/visualization/limesurvey_data.js

    # Auto commits files to the repository
    - name: Auto committing limesurvey results
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: 'assets/js'
        commit_message: "Github Action: Auto Limesurvey results"
        branch: ${{ github.ref }}
    # keep this scheduled action alive. A commit every 60 days is required.
    # This adds a dummy commit if there has been no activity for 50 days
    - uses: gautamkrishnar/keepalive-workflow@v1
